from unittest.mock import patch

import httpx
import pytest
import respx

from schwab_cli.auth_flows import AuthFlowError, get_code
from schwab_cli.config import Config


def _cfg_local() -> Config:
    return Config(
        client_id="cid",
        client_secret="csec",
        redirect_uri="https://127.0.0.1:8443",
        auth_flow="local",
    )


def _cfg_code_relay() -> Config:
    return Config(
        client_id="cid",
        client_secret="csec",
        redirect_uri="https://relay.example.com/uuid/secret",
        auth_flow="code_relay",
        code_relay_url="https://relay.example.com/uuid/secret/wait",
    )


def _cfg_client() -> Config:
    return Config(
        client_id="cid",
        client_secret="csec",
        redirect_uri="https://127.0.0.1:8443",
        auth_flow="client",
    )


def test_get_code_local_dispatches_to_run_full_auth():
    cfg = _cfg_local()
    with patch("schwab_cli.browser.flow.run_full_auth", return_value="LOCAL_CODE"):
        assert get_code(cfg) == "LOCAL_CODE"


def test_get_code_unknown_flow_raises():
    cfg = Config(
        client_id="cid", client_secret="csec",
        redirect_uri="https://127.0.0.1:8443",
        auth_flow="bogus",  # bypasses load() validation
    )
    with pytest.raises(AuthFlowError, match="unknown auth_flow"):
        get_code(cfg)


# ---- code_relay flow ----------------------------------------------------------


@respx.mock
def test_code_relay_returns_code_on_first_poll():
    cfg = _cfg_code_relay()

    captured_state = {}

    def respond(request):
        # Capture the state the flow generated by inspecting webbrowser.open URL.
        return httpx.Response(
            200,
            text=f"code=ABC123&state={captured_state['state']}&other=value",
        )

    respx.get(cfg.code_relay_url).mock(side_effect=respond)

    def fake_open(url):
        # Pull state out of the auth URL the flow built.
        from urllib.parse import parse_qs, urlparse
        captured_state["state"] = parse_qs(urlparse(url).query)["state"][0]
        return True

    with patch("schwab_cli.auth_flows.webbrowser.open", side_effect=fake_open):
        code = get_code(cfg)

    assert code == "ABC123"


@respx.mock
def test_code_relay_handles_long_poll_408_then_success():
    cfg = _cfg_code_relay()

    captured = {}

    def fake_open(url):
        from urllib.parse import parse_qs, urlparse
        captured["state"] = parse_qs(urlparse(url).query)["state"][0]
        return True

    responses = [
        httpx.Response(408, text="timeout"),
        httpx.Response(408, text="timeout"),
        # third call succeeds — body uses the state we captured
    ]

    def respond(request):
        if responses:
            return responses.pop(0)
        return httpx.Response(200, text=f"code=ABC&state={captured['state']}")

    respx.get(cfg.code_relay_url).mock(side_effect=respond)

    with patch("schwab_cli.auth_flows.webbrowser.open", side_effect=fake_open):
        code = get_code(cfg)
    assert code == "ABC"


@respx.mock
def test_code_relay_403_raises_with_helpful_message():
    cfg = _cfg_code_relay()
    respx.get(cfg.code_relay_url).mock(return_value=httpx.Response(403, text="forbidden"))

    with patch("schwab_cli.auth_flows.webbrowser.open", return_value=True):
        with pytest.raises(AuthFlowError, match="Relay rejected"):
            get_code(cfg)


@respx.mock
def test_code_relay_state_mismatch_raises():
    cfg = _cfg_code_relay()
    respx.get(cfg.code_relay_url).mock(
        return_value=httpx.Response(200, text="code=ABC&state=different_state")
    )

    with patch("schwab_cli.auth_flows.webbrowser.open", return_value=True):
        with pytest.raises(AuthFlowError, match="state mismatch"):
            get_code(cfg)


@respx.mock
def test_code_relay_oauth_error_payload_raises():
    cfg = _cfg_code_relay()

    captured = {}

    def fake_open(url):
        from urllib.parse import parse_qs, urlparse
        captured["state"] = parse_qs(urlparse(url).query)["state"][0]
        return True

    def respond(request):
        return httpx.Response(
            200,
            text=f"error=access_denied&error_description=user+canceled&state={captured['state']}",
        )

    respx.get(cfg.code_relay_url).mock(side_effect=respond)

    with patch("schwab_cli.auth_flows.webbrowser.open", side_effect=fake_open):
        with pytest.raises(AuthFlowError, match="access_denied"):
            get_code(cfg)


@respx.mock
def test_code_relay_missing_url_raises_defensively():
    # Bypass loader validation by constructing directly with auth_flow=code_relay
    # and code_relay_url=None.
    cfg = Config(
        client_id="cid", client_secret="csec",
        redirect_uri="https://r/u/s",
        auth_flow="code_relay",
        code_relay_url=None,
    )
    with pytest.raises(AuthFlowError, match="code_relay_url"):
        get_code(cfg)


# ---- client (manual paste) flow ----------------------------------------------


def test_client_extracts_code_from_pasted_url():
    cfg = _cfg_client()

    captured = {}

    def fake_open(url):
        from urllib.parse import parse_qs, urlparse
        captured["state"] = parse_qs(urlparse(url).query)["state"][0]
        return True

    def fake_prompt(label):
        # Echo back the state that was generated, with a code.
        return f"https://127.0.0.1:8443/?code=PASTED_CODE&state={captured['state']}"

    with patch("schwab_cli.auth_flows.webbrowser.open", side_effect=fake_open), \
         patch("schwab_cli.auth_flows.typer.prompt", side_effect=fake_prompt):
        code = get_code(cfg)
    assert code == "PASTED_CODE"


def test_client_state_mismatch_raises():
    cfg = _cfg_client()
    with patch("schwab_cli.auth_flows.webbrowser.open", return_value=True), \
         patch(
             "schwab_cli.auth_flows.typer.prompt",
             return_value="https://127.0.0.1:8443/?code=X&state=wrong",
         ):
        with pytest.raises(AuthFlowError, match="state mismatch"):
            get_code(cfg)


def test_client_missing_query_raises():
    cfg = _cfg_client()
    with patch("schwab_cli.auth_flows.webbrowser.open", return_value=True), \
         patch("schwab_cli.auth_flows.typer.prompt", return_value="https://127.0.0.1:8443/"):
        with pytest.raises(AuthFlowError, match="no query"):
            get_code(cfg)


def test_client_oauth_error_in_url_raises():
    cfg = _cfg_client()

    captured = {}

    def fake_open(url):
        from urllib.parse import parse_qs, urlparse
        captured["state"] = parse_qs(urlparse(url).query)["state"][0]
        return True

    def fake_prompt(label):
        return (
            f"https://127.0.0.1:8443/?error=access_denied"
            f"&error_description=user+canceled&state={captured['state']}"
        )

    with patch("schwab_cli.auth_flows.webbrowser.open", side_effect=fake_open), \
         patch("schwab_cli.auth_flows.typer.prompt", side_effect=fake_prompt):
        with pytest.raises(AuthFlowError, match="access_denied"):
            get_code(cfg)
