"""macOS launchd plist generation for the MCP daemon.

Renders a LaunchAgent plist that runs ``schwab_cli mcp --sse …`` on
login and restarts on exit (``KeepAlive=true``). Lives at
``~/Library/LaunchAgents/com.schwab-cli.mcp.plist``.

Why KeepAlive=true instead of managed-exit: it makes
``schwab_cli mcp restart`` trivial — ``mcp logout`` exits the
daemon cleanly, launchd relaunches with the freshly-installed
code. Stopping permanently is a separate, explicit
``launchctl unload`` via ``mcp uninstall-service`` or
``mcp stop-service``.
"""

from __future__ import annotations

import plistlib
from dataclasses import dataclass
from pathlib import Path


LABEL = "com.schwab-cli.mcp"
LAUNCHER_NAME = "Schwab MCP Server"
DEFAULT_PLIST_PATH = (
    Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"
)


def _launcher_dir() -> Path:
    return (
        Path.home() / "Library" / "Application Support"
        / "schwab_cli" / "launchers"
    )


def launcher_path() -> Path:
    return _launcher_dir() / LAUNCHER_NAME


@dataclass
class LaunchdPlistSpec:
    """Inputs for the plist generator. Kept as a dataclass so tests
    can assert on the generated bytes without a full filesystem round-
    trip."""

    binary_path: str
    host: str = "127.0.0.1"
    port: int = 7234
    log_file: str | None = None      # stderr + stdout destination
    admin_token: str | None = None
    # Override the launcher-script directory. Production callers leave
    # this ``None`` so the launcher lands in the canonical
    # ``~/Library/Application Support/schwab_cli/launchers`` location.
    # Tests must set this to ``tmp_path`` — without an override,
    # ``write_launcher`` clobbers the user's real launcher script.
    launcher_dir: Path | None = None


def _shquote(s: str) -> str:
    """POSIX-shell-quote a path for embedding in the launcher script."""
    if not s or any(c in s for c in " '\"\\$`"):
        return "'" + s.replace("'", "'\\''") + "'"
    return s


def write_launcher(spec: LaunchdPlistSpec) -> Path:
    """Write a tiny shell launcher whose filename is the friendly name.

    macOS uses ``ProgramArguments[0]``'s basename as the System
    Settings → Login Items display label, so a wrapper named
    "Schwab MCP Server" is the simplest way to control that string
    for an unsigned CLI.
    """
    if spec.launcher_dir is not None:
        path = spec.launcher_dir / LAUNCHER_NAME
    else:
        path = launcher_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "#!/bin/sh\n"
        f"# {LAUNCHER_NAME} (auto-generated by schwab_cli)\n"
        f"exec {_shquote(spec.binary_path)} mcp --sse "
        f"--host {_shquote(spec.host)} --port {spec.port} \"$@\"\n"
    )
    path.write_text(body)
    path.chmod(0o755)
    return path


def build_plist(
    spec: LaunchdPlistSpec, *, launcher: Path | None = None,
) -> bytes:
    """Return the plist bytes for ``spec``. Serialized in the XML
    plist format (launchd handles binary too but XML is diffable).

    When ``launcher`` is provided, ``ProgramArguments[0]`` is the
    launcher path — its basename becomes the System Settings display
    name. Without ``launcher``, falls back to direct binary args
    (used by tests / pre-launcher callers)."""
    if launcher is not None:
        program_args = [str(launcher)]
    else:
        program_args = [spec.binary_path, "mcp", "--sse",
                        "--host", spec.host, "--port", str(spec.port)]
    if spec.admin_token:
        # There's no CLI flag for the admin token yet — callers
        # pass it via env only. Reserve the flag plumbing for a
        # future iteration; for now we include it in env.
        pass

    out_log = err_log = None
    if spec.log_file:
        # Rebind stderr/stdout to the log_file so launchd captures
        # anything the daemon writes to those streams even in
        # `--no-log-file` mode.
        out_log = err_log = spec.log_file

    plist: dict[str, object] = {
        "Label": LABEL,
        "ProgramArguments": program_args,
        "RunAtLoad": True,
        "KeepAlive": True,
        "ProcessType": "Interactive",
        "EnvironmentVariables": {
            # Marker so the daemon knows it was launched by launchd
            # (lets `mcp restart` exit 0 instead of execvp-ing a new
            # copy — launchd will auto-restart).
            "LAUNCHD_MANAGED": "1",
        },
    }
    if out_log:
        plist["StandardOutPath"] = out_log
    if err_log:
        plist["StandardErrorPath"] = err_log

    return plistlib.dumps(plist, fmt=plistlib.FMT_XML, sort_keys=True)


def write_plist(
    spec: LaunchdPlistSpec,
    path: Path | None = None,
) -> Path:
    """Write the launcher + plist to disk. Returns the plist path."""
    launcher = write_launcher(spec)
    target = path if path is not None else DEFAULT_PLIST_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(build_plist(spec, launcher=launcher))
    return target


def remove_launcher() -> None:
    """Best-effort delete of the MCP launcher script."""
    p = launcher_path()
    if p.exists():
        p.unlink()
