"""macOS launchd plist generation for the MCP daemon.

Renders a LaunchAgent plist that runs ``schwab_cli mcp --sse …`` on
login and restarts on exit (``KeepAlive=true``). Lives at
``~/Library/LaunchAgents/com.schwab-cli.mcp.plist``.

Why KeepAlive=true instead of managed-exit: it makes
``schwab_cli mcp restart`` trivial — ``mcp logout`` exits the
daemon cleanly, launchd relaunches with the freshly-installed
code. Stopping permanently is a separate, explicit
``launchctl unload`` via ``mcp uninstall-service`` or
``mcp stop-service``.
"""

from __future__ import annotations

import plistlib
from dataclasses import dataclass
from pathlib import Path


LABEL = "com.schwab-cli.mcp"
DEFAULT_PLIST_PATH = (
    Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"
)


@dataclass
class LaunchdPlistSpec:
    """Inputs for the plist generator. Kept as a dataclass so tests
    can assert on the generated bytes without a full filesystem round-
    trip."""

    binary_path: str
    host: str = "127.0.0.1"
    port: int = 7234
    log_file: str | None = None      # stderr + stdout destination
    admin_token: str | None = None


def build_plist(spec: LaunchdPlistSpec) -> bytes:
    """Return the plist bytes for ``spec``. Serialized in the XML
    plist format (launchd handles binary too but XML is diffable)."""
    program_args = [spec.binary_path, "mcp", "--sse",
                    "--host", spec.host, "--port", str(spec.port)]
    if spec.admin_token:
        # There's no CLI flag for the admin token yet — callers
        # pass it via env only. Reserve the flag plumbing for a
        # future iteration; for now we include it in env.
        pass

    log_dir = None
    out_log = err_log = None
    if spec.log_file:
        # Rebind stderr/stdout to the log_file so launchd captures
        # anything the daemon writes to those streams even in
        # `--no-log-file` mode.
        out_log = err_log = spec.log_file

    plist: dict[str, object] = {
        "Label": LABEL,
        "ProgramArguments": program_args,
        "RunAtLoad": True,
        "KeepAlive": True,
        "ProcessType": "Interactive",
        "EnvironmentVariables": {
            # Marker so the daemon knows it was launched by launchd
            # (lets `mcp restart` exit 0 instead of execvp-ing a new
            # copy — launchd will auto-restart).
            "LAUNCHD_MANAGED": "1",
        },
    }
    if out_log:
        plist["StandardOutPath"] = out_log
    if err_log:
        plist["StandardErrorPath"] = err_log

    return plistlib.dumps(plist, fmt=plistlib.FMT_XML, sort_keys=True)


def write_plist(
    spec: LaunchdPlistSpec,
    path: Path | None = None,
) -> Path:
    """Write the generated plist to disk. Parent dir is created if
    needed. Returns the path written to."""
    target = path if path is not None else DEFAULT_PLIST_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(build_plist(spec))
    return target
