"""macOS launchd plist generation for the ``schwab server`` daemon.

Renders a LaunchAgent plist that runs ``schwab server`` on login and
restarts it on exit (``KeepAlive=true``). Lives at
``~/Library/LaunchAgents/com.schwab-cli.server.plist``.

Mirrors :mod:`schwab_cli.mcp_server.launchd`: ``RunAtLoad`` +
``KeepAlive`` + a ``LAUNCHD_MANAGED`` env marker, serialized as diffable
XML plist.
"""

from __future__ import annotations

import plistlib
from dataclasses import dataclass
from pathlib import Path


LABEL = "com.schwab-cli.server"
DEFAULT_PLIST_PATH = (
    Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"
)


@dataclass
class ServerPlistSpec:
    """Inputs for the plist generator.

    Kept as a dataclass so tests can assert on the generated bytes
    without a filesystem round-trip.
    """

    binary_path: str
    log_file: str | None = None      # stderr + stdout destination


def build_plist(spec: ServerPlistSpec) -> bytes:
    """Return the XML plist bytes for ``spec``.

    ``ProgramArguments`` is exactly ``[binary_path, "server"]`` so
    launchd invokes the bare maintenance loop.
    """
    plist: dict[str, object] = {
        "Label": LABEL,
        "ProgramArguments": [spec.binary_path, "server"],
        "RunAtLoad": True,
        "KeepAlive": True,
        "EnvironmentVariables": {
            # Marker so the daemon knows it was launched by launchd.
            "LAUNCHD_MANAGED": "1",
        },
    }
    if spec.log_file:
        plist["StandardOutPath"] = spec.log_file
        plist["StandardErrorPath"] = spec.log_file

    return plistlib.dumps(plist, fmt=plistlib.FMT_XML, sort_keys=True)


def write_plist(
    spec: ServerPlistSpec,
    path: Path | None = None,
) -> Path:
    """Write the plist to disk (creating parents). Returns the path."""
    target = path if path is not None else DEFAULT_PLIST_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(build_plist(spec))
    return target
