"""macOS launchd plist generation for the ``schwab server`` daemon.

Renders a LaunchAgent plist that runs ``schwab server`` on login and
restarts it on exit (``KeepAlive=true``). Lives at
``~/Library/LaunchAgents/com.schwab-cli.server.plist``.

``RunAtLoad`` + ``KeepAlive`` + a ``LAUNCHD_MANAGED`` env marker,
serialized as diffable XML plist.
"""

from __future__ import annotations

import plistlib
from dataclasses import dataclass
from pathlib import Path


LABEL = "com.schwab-cli.server"
DEFAULT_PLIST_PATH = (
    Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"
)


@dataclass
class ServerPlistSpec:
    """Inputs for the plist generator.

    Kept as a dataclass so tests can assert on the generated bytes
    without a filesystem round-trip.

    The ``enable_mcp`` / ``enable_rest`` / ``host`` / ``port`` /
    ``mcp_log_file`` fields bake the ``schwab server`` mode flags into
    the plist's ``ProgramArguments``. With all defaults (no modes) the
    plist runs the bare maintenance loop: ``[binary, "server"]``.
    """

    binary_path: str
    log_file: str | None = None      # stderr + stdout destination
    enable_mcp: bool = False
    enable_rest: bool = False
    host: str | None = None          # MCP bind host (only with enable_mcp)
    port: int | None = None          # MCP bind port (only with enable_mcp)
    mcp_log_file: str | None = None  # MCP structured log (only with enable_mcp)


def _program_arguments(spec: ServerPlistSpec) -> list[str]:
    """Build the ``ProgramArguments`` list, baking in the mode flags.

    Bare (no modes) → ``[binary, "server"]``. ``--host``/``--port``/
    ``--log-file`` are only meaningful alongside ``--enable-mcp`` (they
    configure the MCP listener), so they are appended only then.
    """
    args = [spec.binary_path, "server"]
    if spec.enable_mcp:
        args.append("--enable-mcp")
        if spec.host is not None:
            args += ["--mcp-host", spec.host]
        if spec.port is not None:
            args += ["--mcp-port", str(spec.port)]
        if spec.mcp_log_file is not None:
            args += ["--log-file", spec.mcp_log_file]
    if spec.enable_rest:
        args.append("--enable-rest")
    return args


def build_plist(spec: ServerPlistSpec) -> bytes:
    """Return the XML plist bytes for ``spec``.

    ``ProgramArguments`` is ``[binary_path, "server", *mode_flags]`` —
    bare maintenance loop by default, with ``--enable-mcp`` /
    ``--enable-rest`` (and their host/port/log-file) baked in when set.
    """
    plist: dict[str, object] = {
        "Label": LABEL,
        "ProgramArguments": _program_arguments(spec),
        "RunAtLoad": True,
        "KeepAlive": True,
        # Interactive = scheduled like a user app, so launchd spawns it
        # promptly on load (matches the pre-restructure mcp daemon). Without
        # it the job is treated as background/standard and launchd is lazier
        # about the RunAtLoad spawn.
        "ProcessType": "Interactive",
        "EnvironmentVariables": {
            # Marker so the daemon knows it was launched by launchd.
            "LAUNCHD_MANAGED": "1",
        },
    }
    if spec.log_file:
        plist["StandardOutPath"] = spec.log_file
        plist["StandardErrorPath"] = spec.log_file

    return plistlib.dumps(plist, fmt=plistlib.FMT_XML, sort_keys=True)


def write_plist(
    spec: ServerPlistSpec,
    path: Path | None = None,
) -> Path:
    """Write the plist to disk (creating parents). Returns the path."""
    target = path if path is not None else DEFAULT_PLIST_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(build_plist(spec))
    return target
